### ISSUE TITLE
Binary for 1.3.3

### ISSUE THREAD

**Issue by leonschuetz** [freebayes/freebayes#666]
Hello,

will there be a linux binary for version 1.3.3?

Best Regards,
Leon

**Comment by splaisan** [comment]
same here, 
Also how can we build from source, no page found so far and it seems it is done now with cmake rather than make. Any tutorial would be welcome.

**Comment by jnumm** [comment]
For the build instructions, look at [the final three chapters of README](https://github.com/freebayes/freebayes#development) (for example you can scroll to the bottom of page https://github.com/freebayes/freebayes) :slightly_smiling_face:

**Comment by splaisan** [comment]
Thanks a lot, I found this part after posting and installed ninja to try it.

I did build something but the test command returned errors and I am worried there could be something wrong with the exe now.

Can you make something of the error messages below?

```
ninja test
[1/1] Running all tests.
1/5 T00                                     OK       0.39 s
2/5 T01                                     OK      21.83 s
3/5 T01b                                    FAIL    11.52 s
4/5 T02                                     OK       0.52 s
5/5 T03                                     OK       0.25 s

Output of failed tests (max 10):
T01b stdout:

t/01b_call_variants.t .. 
1..10
not ok 1 - running in parallel makes no difference
#          got: '154'
#     expected: '0'
not ok 2 - freebayes handles spaces in file names
#          got: '154'
#     expected: '0'
ok 3 - freebayes handles region and variant input even with : in contig names
ok 4 - freebayes can handle spliced reads
ok 5 - freebayes produces the expected number of lines of gVCF output
ok 6 - freebayes produces the expected number of lines of gVCF output
ok 7 - freebayes produces the expected number of lines of gVCF output
ok 8 - the CNV map may be used to specify per-sample copy numbers
ok 9 - freebayes makes the expected number of calls when capping coverage
ok 10 - freebayes correctly uses CNV map with multiple entries
Failed 2/10 subtests 

Test Summary Report
-------------------
t/01b_call_variants.t (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  1-2
Files=1, Tests=10, 11 wallclock secs ( 0.02 usr  0.01 sys + 12.50 cusr  0.26 csys = 12.79 CPU)
Result: FAIL


T01b stderr:

../scripts/freebayes-parallel: line 40: vcfstreamsort: command not found
../scripts/freebayes-parallel: line 40: vcfuniq: command not found
Traceback (most recent call last):
  File "../scripts/vcffirstheader", line 16, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe
Warning: unable to close filehandle properly: Broken pipe during global destruction.
../scripts/freebayes-parallel: line 40: vcfuniq: command not found
../scripts/freebayes-parallel: line 40: vcfstreamsort: command not found
Traceback (most recent call last):
  File "../scripts/vcffirstheader", line 16, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe
Warning: unable to close filehandle properly: Broken pipe during global destruction.




Full log written to meson-logs/testlog.txt.
FAILED: '/usr/bin/python3' '/usr/bin/../share/meson/meson' '--internal' 'test' '/opt/biotools/freebayes.git/build/meson-private/meson_test_setup.dat'
ninja: build stopped: subcommand failed.
```

the scripts not found above are present one level higher in the file system (not in build: therefore not found), is thisd OK?

**Comment by pjotrp** [comment]
Above tests fail because vcflib tools are missing. It is harmless, you can use freebayes.

**Comment by splaisan** [comment]
Thanks Piotr,
I believe they are present but not looked for at their right place by the test (scripts is at the same level as build in the tree and the test is run from within build I think).
Or else we should add the path to /scripts to PATH before building in which case this should be added to the readme!
I am not competent enough to check the test code though.
