### ISSUE TITLE
Freebayes 1.3.7 fails its build time test suite.

### ISSUE THREAD

**Issue by nileshpatra** [freebayes/freebayes#786]
**Only bug reports!**

The C++ version of Freebayes is in *maintenance* mode. Use the github issue
tracker to report bugs *only*. For comments, questions and features,
please use the google group mailing list as stated on the
[README](https://github.com/freebayes/freebayes/blob/master/README.md)!

**Describe the bug**

Freebayes 1.3.7 fails its build time test suite full log at: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067271

**To Reproduce**

Build+Run tests

**Expected behavior**

Test Suite should pass

**Additional context**

Backtrace:

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff79a51cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7957472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff79414b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7cd87ee in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00005555555dbc3f in std::vector<Allele*, std::allocator<Allele*> >::operator[] (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/13/bits/stl_vector.h:1123
#6  std::vector<Allele*, std::allocator<Allele*> >::operator[] (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/13/bits/stl_vector.h:1123
#7  multichoose<Allele> (k=2, objects=...) at /usr/include/vcflib/multichoose.h:58
#8  0x00005555555d3d69 in allPossibleGenotypes (ploidy=<optimized out>, potentialAlleles=...) at ../src/Genotype.cpp:356
#9  0x00005555555d44df in getGenotypesByPloidy (ploidies=std::vector of length 1, capacity 1 = {...}, 
    genotypeAlleles=std::vector of length 2, capacity 2 = {...}) at ../src/Genotype.cpp:1741
#10 0x00005555555648ef in main (argc=<optimized out>, argv=<optimized out>) at ../src/freebayes.cpp:331
quit)
```

cc: @pjotrp

**Comment by pjotrp** [comment]
should be fixed in 1.3.8
